#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@qos_guoguo[-1]
	add ucitrack qos_guoguo
	set ucitrack.@qos_guoguo[-1].init=qos_guoguo
	commit ucitrack
EOF

/etc/init.d/qos_guoguo enabled && ( /etc/init.d/qos_guoguo stop ; /etc/init.d/qos_guoguo disable )

rm -f /tmp/luci-indexcache
exit 0
