#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@shadowsocksr-libev[-1]
	add ucitrack shadowsocksr-libev
	set ucitrack.@shadowsocksr-libev[-1].init=shadowsocksr-libev
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
